routes/web.php
<?php



use Illuminate\Support\Facades\Route;
use App\Http\Livewire\BlogIndex;
use App\Http\Livewire\BlogShow;
use App\Http\Livewire\BlogForm;
use App\Http\Livewire\StateIndex;
use App\Http\Livewire\StateShow;

Route::redirect('/register', '/login');

Route::view('/', 'pages.home')->name('home');
Route::view('/about', 'pages.about')->name('about');
Route::view('/services', 'pages.services')->name('services');
Route::view('/process', 'pages.process')->name('process');
Route::view('/locations', 'pages.locations')->name('locations');
Route::view('/faqs', 'pages.faqs')->name('faqs');
Route::view('/privacy-policy', 'pages.privacy-policy')->name('privacy-policy');
Route::view('/nflpa', 'pages.nflpa')->name('nflpa');
Route::view('/quote', 'pages.quote')->name('quote');
Route::view('/quote-nflpa', 'pages.quote-nflpa')->name('quote-nflpa');

Route::middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});



Route::get('/blog', BlogIndex::class)->name('blog.index');
Route::get('/blog/{slug}', BlogShow::class)->name('blog.show');

Route::get('/states', StateIndex::class)->name('states.index');
Route::get('/state/{slug}', StateShow::class)->name('state.show');



Route::get('/create-blog', BlogForm::class)->name('blog.form');


Route::get('sitemap.xml', 'App\Http\Controllers\SitemapController@index');

app/View/Components/MainLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class MainLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.main');
    }
}

resources/views/pages/about.blade.php
<x-main-layout>
    <div class="container mx-auto p-4">
        <div class="flex flex-col p-6">

            <h2 class="text-xl font-bold text-gray-700 mb-4">AUTO TRANSPORT</h2>
            <div class="flex flex-col sm:flex-row">
                <div class="w-full sm:w-1/3">
                    <img class="h-80 w-full object-cover" src="{{asset('/uploads/2022/03/services-1.jpg')}}" alt="">

                </div>
                <div class="w-full sm:w-2/3 p-8 flex items-center">
                    <div>
                        <h4 class="text-xl text-gray-600 font-bold">WE’VE BUILT OUR REPUTATION ON EXCELLENCE IN SHIPPING AND LOGISTICS, WITH A CONSTANT FOCUS ON SERVING OUR CUSTOMERS.</h4>
                        <p class="text-sm text-gray-600 mb-4">When it comes to auto transport we know effective and fast communication is key to client comfort. We provide same day response to your inquiries, from pick-up to delivery, we’ll be there every step of the way.</p>
                        <p class="text-sm text-gray-600 mb-4">You trust us to ship your vehicle, you’ll know that the safe transport of your vehicle is in the hands of skilled, qualified professionals. We only use DOT Licensed drivers who are insured and have a 98% rating or higher.</p>
                        <p class="text-sm text-gray-600 font-bold mb-4">NO TRUCK TRANSFER, YOUR VEHICLE WILL always STAY ON THE SAME CARRIER.</p>
                    </div>
                </div>
            </div>
            <hr>
            <div class="mt-2 md:mt-6">
                <h2 class="text-xl font-bold text-gray-700 mb-4">WHY CHOOSE US?</h2>
                <div class="w-full md:w-2/3 mb-8">
                    <div class="mb-4">
                        <h3 class="text-lg font-bold text-gray-700 mb-2">No Money Up Front</h3>
                        <p class="text-gray-600 text-sm">Many companies preach the fact that they do not charge money upfront yet the fact is that when you attempt to book an order they will ask you for a credit or debit card to take a deposit or down payment.</p>
                    </div>
                    <div class="mb-4">
                        <h3 class="text-lg font-bold text-gray-700 mb-2">Personal Representative</h3>
                        <p class="text-gray-600 text-sm">When you book your order with Dynamic, you will be assigned a personal representative that will deal with you from beginning to end.</p>
                    </div>
                    <div class="mb-4">
                        <h3 class="text-lg font-bold text-gray-700 mb-2">Relationship With Our Drivers</h3>
                        <p class="text-gray-600 text-sm">We understand the value of a customer’s car that is why we feel the need to only deal with drivers that we have formed a professional relationship with during our years in the industry.</p>
                    </div>
                    <div class="mb-4">
                        <h3 class="text-lg font-bold text-gray-700 mb-2">5 Star Rated Company</h3>
                        <p class="text-gray-600 text-sm">At the end of the day we let our customers do the talking for us.</p>
                    </div>
                </div>
            </div>
            <hr>
            <div class="mt-2 md:mt-6">
                <h2 class="text-xl font-bold text-gray-700 mb-4">LATEST NEWS</h2>
                <div class="flex flex-col md:flex-row mb-8">
                    <div class="w-full md:w-1/2 mb-4 md:mb-0">
                        <p class="text-sm text-gray-600 font-bold mb-2">ADVANCED SOFTWARE</p>
                        <p class="text-sm text-gray-600">At a time when other logistics companies are scaling down, we’re betting on the future with latest software and equipment that make us the best choice to be your transportation partner.</p>
                    </div>
                    <div class="w-full md:w-1/2 mb-4 md:mb-0">
                        <p class="text-sm text-gray-600 font-bold mb-2">OUR WORKFORCE IS NOW BETTER</p>
                        <p class="text-sm text-gray-600">We’ve implemented a new training system for all employees that includes cross training in all relevant areas of the company.</p>
                    </div>
                </div>
            </div>
            <hr>
            <div class="mt-2 md:mt-6">
                <h2 class="text-xl font-bold text-gray-700 mb-4">WE ACCEPT</h2>
                <div class="w-full md:w-2/3 mb-8">
                    <img src="{{asset('/uploads/2022/03/credit-cards-1.png')}}" alt="Accepted payment methods">
                </div>
            </div>
        </div>
    </div>
</x-main-layout>

resources/views/pages/locations.blade.php
<x-main-layout>
    <div class="container mx-auto p-4">
        <div class="flex flex-wrap">
            <div class="w-full lg:w-1/2 mb-4 lg:mb-0">
                <iframe title="Google Map" frameborder="0" style="width:100%;min-height:400px" src="https://www.google.com/maps?q=Dynamic%20Auto%20Movers&amp;output=embed&amp;hl=en&amp;z=12"></iframe>
            </div>
            <div class="w-full lg:w-1/2 px-4">
                <h4 class="font-medium text-xl mb-2"><strong>Dynamic Auto Movers</strong></h4>
                <p><strong>13362 SW 128 ST, Miami, FL 33186</strong></p>
                <p>P: 888-210-9906</p>
                <p>E: <a href="mailto:support@dynamicautomovers.com">support@dynamicautomovers.com</a></p>
                <p>H: Monday – Friday: 9:00 AM to 5:00 PM</p>
            </div>
        </div>

    </div>
</x-main-layout>

resources/views/pages/nflpa.blade.php
<x-main-layout>
    <div class="container mx-auto p-4 text-gray-700">
        <div class="mx-auto my-8">
            <img src="{{ asset('uploads/2022/03/nflpa-dya-1.png') }}" alt="Dynamic Auto Movers logo" class="mx-auto mb-4">
            <p class="my-4 text-primary mt-5 font-bold underline bg-gradient-to-tr from-sky-800 to-blue-900 text-white p-6 rounded-lg shadow-md w-full max-w-6xl"><a class="text-primary font-bold" href="/quote-nflpa" target="_blank" rel="noreferrer noopener">Fill out your quote request information here</a></p>
            <hr class="my-8 border-t-2 border-gray-300">
            <p class="my-4 font-bold">At Dynamic Auto Movers we are happy and proud to begin working with the NFLPA for former and current players. Special discounts will apply for every auto, boat, or watercraft transport in the USA. We can accommodate your transportation needs for any route.</p>
            <p class="my-4 text-primary font-bold  bg-gradient-to-tr from-sky-800 to-blue-900 text-white p-6 rounded-lg shadow-md w-full max-w-6xl">All NFLPA members receive 20% on their transport move anywhere in the USA, including Hawaii and Alaska.</p>
            <p class="my-4">From pickup to delivery, Dynamic Auto Movers is committed to providing NFLPA members with outstanding customer services and valuable transportation solutions. Dynamic Auto only uses DOT Licensed carriers who are insured and have a 98% rating or higher.</p>
            <p class="my-4">Here are some of the many services Dynamic provides to all NFLPA members:</p>
            <ul class="list-disc list-inside my-4">
                <li>Open Transport</li>
                <li>Enclosed Transport</li>
                <li>Heavy-Hauling Equipment Transportation</li>
                <li>Boat, Motorcycle, and Recreational Vehicle Shipping</li>
                <li>Classic, Sports, and Exotic Vehicle Transport</li>
            </ul>
            <p class="my-4">During your move (before or after delivery), please be sure to take a photo w/ your vehicle and tag&nbsp;<strong>@dynamicautomovers_</strong>&nbsp;and&nbsp;<strong>@nflpa</strong>&nbsp;on all social media outlets.</p>
            <p class="my-4 font-bold">No Money Up Front</p>
            <p class="my-4">Pay on delivery no need to put down a credit card. Payment could be done on delivery.</p>
            <p class="my-4 font-bold">Personal Representative</p>
            <p class="my-4">When you book your order with Dynamic, you will be assigned a personal representative that will deal with you from beginning to end. We know communication is key, so you’ll be able to text, e-mail, or call this representative at any time.</p>
            <p class="my-4 font-bold">Relationship With Our Drivers</p>
            <p class="my-4">We understand the value of a customer’s car that is why we feel the need to only deal with drivers that we have formed a professional relationship with during our years in the industry. All of our carriers are fully licensed DOT drivers who have a 98% rating or higher. Proof of insurance will also be provided once a reservation is made.</p>
            <p class="my-4 font-bold">5 Star Rated Company</p>
            <p class="my-4">At the end of the day, we let our customers do the talking for us. Feel free to check out our reviews and ratings. You’ll see there are over 700 reviews on google and an A BBB rating and accreditation.</p>
            <p class="my-4 font-bold">To Begin The Process, It’s Simple.</p>
            <p class="my-4 text-primary font-bold underline bg-gradient-to-tr from-sky-800 to-blue-900 text-white p-6 rounded-lg shadow-md w-full max-w-6xl"><a class="text-primary font-bold" href="/quote-nflpa" target="_blank" rel="noreferrer noopener">Fill out your quote request information here</a></p>
            <p class="my-4">A representative will then reach out to you to give you a price and begin the process. We are looking forward to transporting your vehicle!</p>
            <p class="my-4 text-primary font-bold">Dynamic Auto Movers</p>
            <p class="my-4 text-primary font-bold">888-210-9906</p>
        </div>
    </div>
</x-main-layout>

resources/views/pages/privacy-policy.blade.php
<x-main-layout>
    <div class="container mx-auto p-4">
        <div class="flex flex-col items-center p-6">
            <div class="p-4 border-2 border-gray-400 rounded">
                <h1 class="text-2xl font-bold">PRIVACY POLICY</h1>
                <p class="text-base font-medium">
                    We are committed to communicating with you in a professional manner and protecting your confidential information. We use the information you provide (e.g. name, address, phone number, email, agreement to receive newsletter/sales offers etc.) to contact you to share information about our (products/services). We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request. This company does not sell, trade or rent your personal information to others.
                </p>
                <p class="text-base font-medium">
                    Unless you ask us not to, we may contact you via email in the future with news about our company or information about our services. If you subscribe to our newsletter, you may unsubscribe at any time, either by using the unsubscribe link on the newsletter or contacting us via the email address given on our website.
                </p>
                <p class="text-base font-medium">
                    Please contact us at <a href="mailto:support@dynamicautomovers.com" class="font-medium underline">support@dynamicautomovers.com</a> to correct or update information at any time. (provide form or phone number)
                </p>
                <h2 class="text-xl font-bold mt-4">LOGGING AND COOKIES</h2>
                <p class="text-base font-medium">
                    When you browse our website, the following information about your visit is collected and stored: the computer’s Internet Protocol (IP) address (a number automatically assigned to your computer when you access the Internet); the domain from which you access the Internet (for example: aol.com, for an America Online account), the website address from which you came to our site (for example: www.google.com, if you came by clicking a link from a Google search); the date and time you arrived at our site and how long you spent here; the name and version of your computer’s operating system and browser Example: Windows 7/Internet Explorer 8.0; the pages you visited.
                </p>
                <p class="text-base font-medium">
                    We also use “cookies” on this site. A cookie is a piece of data stored on a site visitor’s hard drive to help us further determine usage of our site and sources of site traffic, improve access to our site and identify repeat visitors.
                </p>
                <h2 class="text-xl font-bold mt-4">LINKS</h2>
                <p class="text-base font-medium">
                    This website may contain links to other sites. Please be aware that we are not responsible for the content or privacy practices of such other sites.
                </p>
            </div>
        </div>
    </div>
</x-main-layout>

resources/views/pages/process.blade.php
<x-main-layout>
<div class="container mx-auto p-4">
    <div class="flex flex-col p-6">
        <p class="font-light mb-10">Overwhelmed with a large array of quotes ranging from all sorts of different prices? Weary of so many companies calling you and offering you the world? We are aware of how flustering the quote receiving process can be so our job is to take that stress of your hands and worries of your mind. Our goal is to make this as simple a process for our customers so transporting your vehicle can become a care-free ordeal. We have put together a 10 step process so that you can understand exactly what goes into the process of transporting a car and can be on the same page as us every step of the way!</p>
        <h5 class="font-medium mb-5">1. CHOOSE US!</h5>
        <p class="font-light mb-10">Once you have decided to use DAM as your preferred vehicle shipper there are two ways to schedule a pick-up: Online or calling our direct line and scheduling your shipment with your assigned representative.</p>
        <h5 class="font-medium mb-5">2. CARRIER SEARCH</h5>
        <p class="font-light mb-10">The priority is to meet our customer’s needs, so we take down your desired transport date as well as your pickup and delivery address so we can properly search for the driver that will most suit your particular move. We take pride in not asking our customers for a down payment or deposit at this point like our competitors do, we do not get paid until our job is done!</p>
        <h5 class="font-medium mb-5">3. CHOOSING A CARRIER</h5>
        <p class="font-light mb-10">Your transport organizer will call you to present the different options he has researched so both you and him can decide on the one that will most suit your needs.</p>
        <h5 class="font-medium mb-5">4. BOOKING THE SPOT</h5>
        <p class="font-light mb-10">Once a carrier has been designated a spot will be booked and two emails will be sent to you. The first one is the vehicle dispatch sheet which contains all the information related to your move. We want you to feel comfortable and thus provide the carrier’s name and number, the pick-up and delivery dates that carrier has committed to, along with the total price that the trucker has signed for therefore eliminating the fear of truckers showing up and asking for more money. The second email is the company agreement that can easily be completed electronically.​</p>
        <h5 class="font-medium mb-5">5. SCHEDULING A TIME</h5>
        <p class="text-base font-light mb-5">The day before the pick up, the carrier will call you to provide an estimated window of time for arrival. This will be followed up with another call when the driver is one hour away. This way, you can continue with your day as planned without having to wait around all day.</p>
        <h5 class="font-medium mb-5">6. PICK UP PROCESS</h5>
        <p class="text-base font-light mb-5">The pick-up process is easy. You and the driver will perform a full inspection of the vehicle to note any scratches or dents. This is important for your protection against any potential damage that may occur during transport, as well as for the carrier to ensure that no damage was induced during transport. The bill of lading will then be signed by both parties, and the driver will safely load the car onto the carrier and be on their way.</p>
        <h5 class="font-medium mb-5">7. SCHEDULING DELIVERY</h5>
        <p class="text-base font-light mb-5">The delivery process is the same as the pick-up process. Within 24 hours of delivery, the driver will contact you to schedule a convenient window for delivery. The driver will again call you an hour before delivery to confirm the time.</p>
        <h5 class="font-medium mb-5">8. DELIVERY PROCESS</h5>
        <p class="text-base font-light mb-5">The driver will unload the vehicle, and both parties will inspect the car. Please be thorough to avoid any misunderstandings.</p>
        <h5 class="font-medium mb-5">9. TELL US HOW YOUR EXPERIENCE WAS</h5>
        <p class="text-base font-light mb-5">We encourage you to provide feedback on your experience with us, whether good or bad. If we did a good job, let us know. If there's anything we could have done better, please let us know. We are always striving to improve and the best way to do so is through our customers' opinions.</p>
        <h5 class="font-medium mb-5">10. SAVE OUR CONTACT INFO</h5>
        <p class="text-base font-light mb-5">Were you happy with our service? Did you enjoy working with your personal representative? Save our number and email! Our goal is to build lifelong relationships with our customers so that we can be your transporter of choice. Whether you're a dealer, car collector, student, worker, or a snowbird, we want to be the company you work with. Call us back directly to get the best rates and premium customer service that we are known for.</p>
    </div>
</div>
</x-main-layout>

resources/views/pages/quote-nflpa.blade.php
<x-main-layout>
    <section class="flex h-screen w-full justify-center items-center bg-gray-300">
        @livewire('n-f-l-p-a-quote-form')
    </section>
</x-main-layout>

resources/views/pages/quote.blade.php
<x-main-layout>
    <section class="flex h-screen w-full justify-center items-center bg-gray-300">
        @livewire('main-quote-form')
    </section>
</x-main-layout>

resources/views/pages/services.blade.php
<x-main-layout>
    <div class="container mx-auto p-4">
        <div class="grid grid-cols-1 gap-4 md:flex-row justify-center p-6 text-sky-700 max-w-7xl mx-auto">
            <div class="aspect-w-16 aspect-h-9">
                <iframe class="inset-0" src="https://player.vimeo.com/video/583561242?autoplay=0&amp;title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;controls=1&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
        <div class="flex flex-col items-center p-6">
            <div class="w-full  mb-8 md:mb-4">
                <h4 class="text-tertiary text-lg font-medium">OPEN TRANSPORT:</h4>
                <p class="text-gray-700">Standard method of transport for the industry. 90% of transports are processed this way including our dealership to dealership transfers. Safe and secure, vehicles are strapped with soft ties on our top of the line carriers and not moved throughout the process.</p>
            </div>

            <div class="w-full mb-8 md:mb-4">
                <h4 class="text-tertiary text-lg font-medium">ENCLOSED TRANSPORT:</h4>
                <p class="text-gray-700">The red carpet of transports. We provide hard side enclosed trucks with lift gates so your vehicle receives the treatment it deserves. Cars will be delivered in the same exact condition they were picked up in. Factors such as dirt, dust and debris are completely nullified.</p>
            </div>

            <div class="w-full mb-8 md:mb-4">
                <h4 class="text-tertiary text-lg font-medium">EXOTIC CAR TRANSPORT:</h4>
                <p class="text-gray-700">We are professional transporters of exotic car transports. Insured, bonded and reliable, we are capable of shipping any type of exotic vehicle door to door.</p>
            </div>

            <div class="w-full mb-8 md:mb-4">
                <h4 class="text-tertiary text-lg font-medium">CLASSIC CAR TRANSPORT:</h4>
                <p class="text-gray-700">We have been hauling antiques for years and have a large network of classic car collectors as clients. Our drivers are aware of the importance and value of such vehicles and handle them with extreme care.</p>
            </div>

            <div class="w-full mb-8 md:mb-4">
                <h4 class="text-tertiary text-lg font-medium">MOTORCYCLE TRANSPORTATION:</h4>
                <p class="text-gray-700">We have a dedicated team specifically for motorcycle transportation, this includes: Snowmobile, Jet-Ski and ATV. We have a specialized shipping system designed to protect your vehicle.</p>
            </div>

            <div class="w-full mb-8 md:mb-4">
                <h4 class="text-tertiary text-lg font-medium">BOAT TRANSPORT:</h4>
                <p class="text-gray-700">We can transport: Sailboats, speedboats, yachts and any other type of aqua vehicle.</p>
            </div>

            <div class="w-full mb-8 md:mb-4">
                <h4 class="text-tertiary text-lg font-medium">HEAVY HAULING EQUIPMENT:</h4>
                <p class="text-gray-700">Whether it be tractors, bulldozers, tow trucks or any other unique or oversized vehicle we can transport it.</p>
            </div>
        </div>
    </div>
</x-main-layout>